version: '3.8'

x-common-variables: &common-variables
  KONG_DATABASE: postgres
  KONG_PG_DATABASE: kong
  KONG_PG_HOST: kong-db
  KONG_PG_USER: konguser
  KONG_PG_PASSWORD: konguser

services:
  keycloak:
    image: jboss/keycloak:11.0.3
    container_name: keycloak
    hostname: keycloak
    depends_on:
      - kong-db
    command:
      [
        '-b',
        '0.0.0.0',
        '-Djboss.socket.binding.port-offset=1000',
        '-Dkeycloak.migration.action=import',
        '-Dkeycloak.migration.provider=singleFile',
        '-Dkeycloak.migration.file=/tmp/realm-config/master-realm.json',
        '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING',
        '-Dkeycloak.profile.feature.upload_scripts=enabled',
      ]
    ports:
      - 9080:9080/tcp
    environment:
      #KEYCLOAK_USER: local
      #KEYCLOAK_PASSWORD: local
      DB_ADDR: kong-db:5432
      DB_USER: keycloakuser
      DB_PASSWORD: keycloakuser
    volumes:
      - ./local/keycloak/master-realm.json:/tmp/realm-config/master-realm.json
    networks:
      keycloak:
        aliases:
          - keycloak.localtest.me
      kong-net: {}
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.3
    container_name: oauth2-proxy
    command: --config ./oauth2-proxy.cfg
    depends_on:
      - keycloak
    ports:
      - 4180:4180/tcp
    volumes:
      - ./local/oauth2-proxy/oauth2-proxy-local.cfg:/oauth2-proxy.cfg
    restart: unless-stopped
    env_file:
      - .env.local
    networks:
      keycloak: {}
      portal: {}
      kong-net: {}
      redis-net: {}
      oauth2-proxy:
        aliases:
          - oauth2proxy.localtest.me
  apsportal:
    container_name: apsportal
    image: apsportal:latest
    depends_on:
      - keycloak
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    ports:
      - 3000:3000
    networks:
      portal:
        aliases:
          - apsportal.localtest.me
      keycloak: {}
      oauth2-proxy: {}
      kong-net: {}
  feeder:
    container_name: feeder
    image: feeder:latest
    depends_on:
      - oauth2-proxy
    build:
      context: ./feeds
      dockerfile: Dockerfile
    env_file:
      - ./feeds/.env.local
    restart: on-failure
    ports:
      - 6000:6000
    networks:
      portal:
        aliases:
          - feeder.localtest.me
      kong-net: {}
  feeder-seeding:
    container_name: feeder-seeding
    image: feeder:latest
    command: ''
    entrypoint: sh -c "chmod +x /tmp/init.sh && sh /tmp/init.sh"
    restart: on-failure
    depends_on:
      - feeder
    volumes:
      - ./local/feeder-init:/tmp
    networks:
      - portal
      - keycloak
  cypress:
    image: 'aps-cypress-e2e:latest'
    container_name: cypress-e2e
    entrypoint: sh -c "chmod +x /tmp/entrypoint.sh && /tmp/entrypoint.sh"
    depends_on:
      - feeder-seeding
    build:
      context: ./e2e
      dockerfile: Dockerfile
    volumes:
      - ./e2e/results/report:/e2e/results/report
    networks:
      - keycloak
      - oauth2-proxy
  kong-db:
    image: postgres:latest
    container_name: kong-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: on-failure
    tty: true
    ports:
      - 5432:5432
    volumes:
      - ./local/db/database-init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./local/db/keystone-init.sql:/docker-entrypoint-initdb.d/2-init.sql
    networks:
      - kong-net
      - keycloak
      - portal
  kong-migrations:
    image: kong:latest
    command: kong migrations bootstrap
    depends_on:
      - kong-db
    environment: *common-variables
    networks:
      - kong-net
    restart: on-failure
  kong-migrations-up:
    image: kong:latest
    command: kong migrations up && kong migrations finish
    depends_on:
      - kong-db
    environment: *common-variables
    networks:
      - kong-net
    restart: on-failure
  kong:
    image: kong:latest
    container_name: kong
    depends_on:
      - kong-migrations
      - kong-migrations-up
    environment:
      <<: *common-variables
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_CASSANDRA_CONTACT_POINTS: kong-db
      KONG_NGINX_WORKER_PROCESSES: '1'
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - 8000:8000
      - 8001:8001
    networks:
      kong-net:
        aliases:
          - kong.localtest.me
    restart: on-failure:5
  redis:
    image: bitnami/redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=s3cr3t
    restart: on-failure
    ports:
      - 6379:6379
    networks:
      redis-net:
        aliases:
          - redis.localtest.me
networks:
  keycloak: {}
  oauth2-proxy: {}
  portal: {}
  kong-net: {}
  redis-net: {}
